### ISSUE TITLE
AssertionError in unpack_pbpack.py

### ISSUE THREAD

**Issue by cmaxl** [abl/pbw-tools#10]
What is wrong with your code?
It seems like you're handlin "AssertionErrors" wrong ...?

```
Processing "app_resources.pbpack"
Traceback (most recent call last):
  File "unpack_pbpack.py", line 56, in <module>
    p = PBPack(open("app_resources.pbpack"))
  File "unpack_pbpack.py", line 38, in __init__
    self.resources.append(Resource(resource_block[offset:offset+16], pack))
  File "unpack_pbpack.py", line 22, in __init__
    self.png = BMPResource(self.raw_data)
  File "unpack_pbpack.py", line 10, in __init__
    assert(self.unknown_1 == 4096)
AssertionError
```

**Comment by abl** [comment]
This repo predates the Pebble SDK 1.0 release; the assertions are in there because we had no idea what those values were (but the Pebble OS seemed to care they were exactly those values.)

This repo is probably only useful for looking at the history of Pebble and not for any modern PBWs.
